name: meshtastic_proto
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  dio: ^4.0.4
  protobuf: ^2.0.1
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
